## This version of the script is only usable for Helm API version 2 and below
parameters:
  - name: helmVersion
    type: string
    default: 'latest'
  - name: acrName
    type: string
  - name: azureSubscription
    type: string
  - name: repositoryName
    type: string
  - name: chartName
    type: string
  - name: chartPath
    type: string
  - name: imageTag
    type: string
    default: "$(Build.BuildNumber)"

steps:

  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: ${{ parameters.helmVersion }}

  - task: AzureCLI@2
    displayName: 'Push ${{ parameters.chartName }} to ${{ parameters.acrName }}'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |

        echo "Sign into ${acrName}"
        az acr login --name $acrName

        REPOTRIM="$(echo $chartName | sed 's/-//g')"

        echo "Add Helm Repo to ACR"
        helm repo add $acrName https://$acrName.azurecr.io/helm/v1/repo

        cd $chartPath

        echo "Update Dependencys"
        helm dependency update

        echo "Package Chart in ${chartPath}"
        helm package . --version $imageTag

        echo "Push to ACR with tag $imageTag"
        helm push $chartName-$imageTag.tgz oci://$acrName.azurecr.io/helm
        
    env:
      acrName: "${{ parameters.acrName }}"
      repositoryName: "${{ parameters.repositoryName }}"
      chartName: "${{ parameters.chartName }}"
      chartPath: "${{ parameters.chartPath }}"
      imageTag: "${{ parameters.imageTag }}"