parameters:
  - name: acrName
    type: string
  - name: azureSubscription
    type: string
  - name: imageName
    type: string
  - name: repositoryName
    type: string
  - name: imageTags
    type: object

steps:
  - task: gitversion/setup@3.0.3
    displayName: Install GitVersion
    inputs:
      versionSpec: '6.0.x'

  - task: gitversion/execute@3.0.3
    displayName: Determine Version
      
  - task: AzureCLI@2
    displayName: 'Push ${{ parameters.imageName }} to ${{ parameters.acrName }}'
    name: pushImage
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $tags= $env:tags | ConvertFrom-Json
        $repositoryName=$env:repositoryName
        $imageName=$env:imageName
        $acrName=$env:acrName

        Write-Host "$tags"
        Write-Host "$repositoryName"
        Write-Host "$imageName"
        Write-Host "$acrName"

        Write-Host "List Images"
        docker images

        Write-Host "Sign Into ACR $acrName"
        az acr login --name $acrName

        foreach ($tag in $tags){

          Write-Host "Process Tag $tag"

          $date=$(Get-Date -Format yyyyMMddHHmm);
          $commitId="$(Build.SourceVersion)"
          $shorterCommitId=$commitId.SubString(0,7)

          $newTag= $tag -replace "#{DATETIME}#", $date -replace "#{SHORTCOMMITID}#", $shorterCommitId
          Write-Host "##[command]NEW TAG : $newTag"

          $imageTag="$acrName.azurecr.io/${repositoryName}:$newTag"

          Write-Host "##vso[task.setvariable variable=fullImageName;isOutput=true]$imageTag"

          docker tag $imageName $imageTag
          
          Write-Host "Push $imageTag"
          docker push $imageTag
        }
    env:
      acrName: "${{ parameters.acrName }}"
      repositoryName: "${{ parameters.repositoryName }}"
      imageName: "${{ parameters.imageName }}"
      tags: ${{ convertToJson(parameters.imageTags) }}