parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: releaseParameters
  type: object
  default: {}

- name: environments
  type: object
  default: []

stages:
- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), containsValue(parameters.environments, 'Preview')) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Preview
      stageName: Preview
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      variables:
        - group: vh-preview
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), containsValue(variable.env, 'Preview')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), eq(variables['${{parameters.deploymentBranch}}'], 'refs/heads/master'))

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), containsValue(parameters.environments, 'Dev')) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Dev
      stageName: Dev
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      variables:
        - group: vh-dev
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), containsValue(variable.env, 'Dev')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), eq(variables['${{parameters.deploymentBranch}}'], 'refs/heads/master'))

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), containsValue(parameters.environments, 'AAT')) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: AAT
      stageName: AAT
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      variables:
        - group: vh-aat
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), containsValue(variable.env, 'AAT')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), eq(variables['${{parameters.deploymentBranch}}'], 'refs/heads/master'))

- ${{ if containsValue(parameters.environments, 'Demo') }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Demo
      stageName: Demo
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      variables:
        - group: vh-demo
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), containsValue(variable.env, 'Demo')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}

- ${{ if containsValue(parameters.environments, 'Sandbox') }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Sandbox
      stageName: Sandbox
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      variables:
        - group: vh-sandbox
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), containsValue(variable.env, 'Sandbox')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), eq(variables['${{parameters.deploymentBranch}}'], 'refs/heads/master'))

- ${{ if contains(join(';',parameters.environments), 'Test') }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
    # add below if block for new test* envs
      ${{ if contains(join(';',parameters.environments), 'Test1') }}:
        environment: Test1
        stageName: Test1
      ${{ if contains(join(';',parameters.environments), 'Test2') }}:
        environment: Test2
        stageName: Test2
    # end
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      variables:
      # add below if block for new test* envs
        - ${{ if contains(join(';',parameters.environments), 'Test1') }}:
          - group: vh-test1
        - ${{ if contains(join(';',parameters.environments), 'Test2') }}:
          - group: vh-test2
      # end
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), contains(join(';',variable.env), 'Test')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), and(containsValue(parameters.environments, 'Preprod'), or(startsWith(parameters.deploymentBranch, 'refs/heads/release/'), startsWith(parameters.deploymentBranch, 'refs/heads/hotfix/')))) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Preprod
      stageName: Preprod
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      variables:
        - group: vh-preprod
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), containsValue(variable.env, 'Preprod')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), or(startsWith(variables['${{parameters.deploymentBranch}}'], 'refs/heads/release/'), startsWith(variables['${{parameters.deploymentBranch}}'], 'refs/heads/hotfix/')))

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), and(containsValue(parameters.environments, 'Prod'), or(startsWith(parameters.deploymentBranch, 'refs/heads/release/'), startsWith(parameters.deploymentBranch, 'refs/heads/hotfix/')))) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Prod
      stageName: Prod
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deployBranch: $(${{ parameters.deploymentBranch }})
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        dependantStages:
          - Preprod
      variables:
        - group: vh-prod
        - runACTests: ${{ variables.runACTests }}
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if or(not(variable.env), containsValue(variable.env, 'Prod')) }}:
              - ${{ if eq('group', property.key) }}:
                - group: ${{ variable.group }}
              - ${{ if eq('name', property.key) }}:
                - name: ${{ variable.name }}
                  value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), or(startsWith(variables['${{parameters.deploymentBranch}}'], 'refs/heads/release/'), startsWith(variables['${{parameters.deploymentBranch}}'], 'refs/heads/hotfix/')))
