parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: releaseParameters
  type: object
  default: {}

- name: environments
  type: object

stages:
- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), containsValue(parameters.environments, 'Preview')) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Preview
      stageName: Preview
      deployBranch: ${{ parameters.deploymentBranch }}
      variables:
        - group: vh-preview
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), eq('${{parameters.deploymentBranch}}', 'refs/heads/master'))

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), containsValue(parameters.environments, 'Dev')) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Dev
      stageName: Dev
      deployBranch: ${{ parameters.deploymentBranch }}
      variables:
        - group: vh-dev
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), eq('${{parameters.deploymentBranch}}', 'refs/heads/master'))

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), containsValue(parameters.environments, 'AAT')) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: AAT
      stageName: AAT
      deployBranch: ${{ parameters.deploymentBranch }}
      variables:
        - group: vh-aat
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        condition: and(succeeded(), eq('${{parameters.deploymentBranch}}', 'refs/heads/master'))

- ${{ if containsValue(parameters.environments, 'Demo') }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Demo
      stageName: Demo
      deployBranch: ${{ parameters.deploymentBranch }}
      variables:
        - group: vh-demo
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}

- ${{ if containsValue(parameters.environments, 'Sandbox') }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Sandbox
      stageName: Sandbox
      deployBranch: ${{ parameters.deploymentBranch }}
      variables:
        - group: vh-sandbox
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}

- ${{ if containsValue(parameters.environments, 'Test1') }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Test1
      stageName: Test1
      deployBranch: ${{ parameters.deploymentBranch }}
      variables:
        - group: vh-test1
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), and(containsValue(parameters.environments, 'Preprod'), or(startsWith(parameters.deploymentBranch, 'refs/heads/release/'), startsWith(parameters.deploymentBranch, 'refs/heads/hotfix/')))) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Preprod
      stageName: Preprod
      deployBranch: ${{ parameters.deploymentBranch }}
      variables:
        - group: vh-preprod
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      condition: and(succeeded(), or(startsWith('${{parameters.deploymentBranch}}', 'refs/heads/release/'), startsWith('${{parameters.deploymentBranch}}', 'refs/heads/hotfix/')))

- ${{ if or(eq(variables['Build.Reason'], 'ResourceTrigger'), and(containsValue(parameters.environments, 'Prod'), or(startsWith(parameters.deploymentBranch, 'refs/heads/release/'), startsWith(parameters.deploymentBranch, 'refs/heads/hotfix/')))) }}:
  - template: ..\stages\dotnet-release.yml
    parameters:
      environment: Prod
      stageName: Prod
      deployBranch: ${{ parameters.deploymentBranch }}
      dependantStages:
        - Preprod
      variables:
        - group: vh-prod
        - ${{ each variable in parameters.releaseParameters.variables }}:
          - ${{ each property in variable }}:
            - ${{ if eq('group', property.key) }}:
              - group: ${{ variable.group }}
            - ${{ if eq('name', property.key) }}:
              - name: ${{ variable.name }}
                value: ${{ variable.value }}
      ${{ each setting in parameters.releaseParameters }}:
        ${{ if ne(setting.key, 'variables') }}:
          ${{ setting.key }}: ${{ setting.value }}
      condition: and(succeeded(), or(startsWith('${{parameters.deploymentBranch}}', 'refs/heads/release/'), startsWith('${{parameters.deploymentBranch}}', 'refs/heads/hotfix/')))
