parameters:
  - name: baseAgent
    type: string
    default: Ubuntu-16.04

  - name: dotnetContainer
    type: string
    default: dotnetsdk

  - name: vstsFeedId
    type: string
    default: 3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5

  - name: coreProjectPath
    type: string

  - name: nodeProjectPath
    type: string
    default: ''

  - name: dependantStages
    type: object
    default: []

  - name: packageManagers
    type: object
    default:
     - nuget

  - name: PackageApp
    type: boolean
    default: true
  - name: PackageAcceptanceTests
    type: boolean
    default: true

  - name: Test
    type: boolean
    default: false

  - name: NodeTest
    type: boolean
    default: false

  - name: ACTest
    type: boolean
    default: false

  - name: testParameters
    type: object
    default: {}

  - name: nodeTestParameters
    type: object
    default: {}

  - name: releaseParameters
    type: object
    default: {}

stages:
- ${{ if or(parameters.PackageApp, parameters.PackageAcceptanceTests, parameters.ACTest) }}:
  - stage: Package
    dependsOn:
    - ${{ if parameters.dependantStages }}:
      - ${{ parameters.dependantStages }}

    variables:
      - template: ../templates/variables/packageManagers.yml

    jobs:
    - ${{ if or(parameters.PackageApp, parameters.ACTest) }}:
      - job: Publish_App

        pool:
          vmImage: ${{ parameters.baseAgent }}

        container: ${{ parameters.dotnetContainer }}

        dependsOn: []

        steps:
        - checkout: self

        - task: gittools.gitversion.gitversion-task.GitVersion@5
          displayName: GitVersion
          inputs:
            additionalArguments: /updateassemblyinfo ${{ parameters.coreProjectPath }}/AssemblyInfo.cs /ensureassemblyinfo

        - template: ../templates/pipelineCaching.yml
          parameters:
            ${{ if containsValue(parameters.packageManagers, 'nuget') }}:
              nugetProjectPath: ${{ parameters.coreProjectPath }}
            ${{ if containsValue(parameters.packageManagers, 'npm') }}:
              nodeProjectPath: ${{ parameters.nodeProjectPath }}
            ${{ if containsValue(parameters.packageManagers, 'yarn') }}:
              yarnProjectPath: ${{ parameters.nodeProjectPath }}
            packageManagers:
            - ${{ if parameters.packageManagers }}:
              - ${{ parameters.packageManagers }}

        - task: DotNetCoreCLI@2
          displayName: dotnet Restore
          inputs:
            command: restore
            projects: ${{ parameters.coreProjectPath }}/*.csproj
            vstsFeed: ${{ parameters.vstsFeedId }}
            includeNuGetOrg: true
            restoreArguments: --locked-mode --use-lock-file
          condition: ne(variables.NUGET_CACHE_RESTORED, 'true')

        - task: DotNetCoreCLI@2
          displayName: donet Publish
          inputs:
            command: publish
            publishWebProjects: false
            arguments: --configuration Release --output $(build.artifactstagingdirectory)/App
            zipAfterPublish: True
            workingDirectory: ${{ parameters.coreProjectPath }}

        - task: PublishBuildArtifacts@1
          displayName: Publish App
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)/App
            ArtifactName: App

    - ${{ if or(parameters.PackageAcceptanceTests, parameters.ACTest) }}:
      - job: Publish_AcceptanceTests

        pool:
          vmImage: ${{ parameters.baseAgent }}

        container: ${{ parameters.dotnetContainer }}

        dependsOn: []

        steps:
        - checkout: self

        - task: gittools.gitversion.gitversion-task.GitVersion@5
          displayName: GitVersion
          inputs:
            additionalArguments: /updateassemblyinfo ${{ parameters.coreProjectPath }}.AcceptanceTests/AssemblyInfo.cs /ensureassemblyinfo

        - template: ../templates/pipelineCaching.yml
          parameters:
            ${{ if containsValue(parameters.packageManagers, 'nuget') }}:
              nugetProjectPath: ${{ parameters.coreProjectPath }}.AcceptanceTests
            packageManagers:
            - nuget

        - task: DotNetCoreCLI@2
          displayName: dotnet Restore
          inputs:
            command: restore
            projects: '**/*AcceptanceTests.csproj'
            vstsFeed: ${{ parameters.vstsFeedId }}
            includeNuGetOrg: true
            restoreArguments: --locked-mode --use-lock-file
          condition: ne(variables.NUGET_CACHE_RESTORED, 'true')

        - task: DotNetCoreCLI@2
          displayName: donet Publish
          inputs:
            command: publish
            publishWebProjects: false
            arguments: --configuration Release --output $(build.artifactstagingdirectory)/AcceptanceTests
            zipAfterPublish: false
            workingDirectory: ${{ parameters.coreProjectPath }}.AcceptanceTests

        - task: PublishBuildArtifacts@1
          displayName: Publish AcceptanceTests
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)/AcceptanceTests
            ArtifactName: AcceptanceTests

- ${{ if ne(variables['Build.Reason'], 'IndividualCI') }}:
  - ${{ if eq(parameters.Test, true) }}:
    - template: ./dotnet-test.yml
      parameters:
        ${{ insert }}: ${{ parameters.testParameters }}

  - ${{ if eq(parameters.NodeTest, true) }}:
    - template: ./node-test.yml
      parameters:
        ${{ insert }}: ${{ parameters.nodeTestParameters }}

  - ${{ if eq(parameters.ACTest, true)}}:
    - template: ./dotnet-release.yml
      parameters:
        dependantStages: Package
        useCurrentPipeline: true
        stageName: AcceptanceTest
        runZapTests: ${{ coalesce(parameters.releaseParameters.runZapTests, true) }}
        ${{ each setting in parameters.releaseParameters }}:
          ${{ if ne(setting.key, 'runZapTests') }}:
            ${{ setting.key }}: ${{ setting.value }}
